import type { IBaseItemDefinition } from "./types";

export type IBaseItemEquipmentTypeType = "weapon" | "offhand" | "armour" | "jewellery";
export type IBaseItemSubTypeType =
  | "dagger"
  | "oneHandSword"
  | "oneHandAxe"
  | "oneHandMace"
  | "sceptre"
  | "spear"
  | "flail"
  | "staff"
  | "wand"
  | "bow"
  | "claw"
  | "twoHandSword"
  | "twoHandAxe"
  | "twoHandMace"
  | "quarterstaff"
  | "fishingRod"
  | "crossbow"
  | "trap"
  | "talisman"
  | "quiver"
  | "shield"
  | "buckler"
  | "helmet"
  | "focus"
  | "gloves"
  | "bodyArmour"
  | "boots"
  | "amulet"
  | "ring"
  | "belt";

export interface IBaseItemDbRecordType {
  baseItemKey: string;
  itemClass: string;
  itemClassKey: IBaseItemSubTypeType;
  equipmentType: IBaseItemEquipmentTypeType;
  subType: IBaseItemSubTypeType;
  requiredStrength: number;
  requiredDexterity: number;
  requiredIntelligence: number;
  levelRequirement: number;
  source: "poe2db";
  sourceUrl: string;
  /** i18n keys referencing `simulator.baseItemImplicits.*` */
  implicitMods?: ReadonlyArray<string>;
}

export interface IBaseItemDbType {
  version: string;
  records: ReadonlyArray<IBaseItemDbRecordType>;
}

export const BASE_ITEM_SUB_TYPES_BY_EQUIPMENT: Readonly<
  Record<IBaseItemEquipmentTypeType, ReadonlyArray<IBaseItemSubTypeType>>
> = {
  weapon: [
    "claw",
    "dagger",
    "wand",
    "oneHandSword",
    "oneHandAxe",
    "oneHandMace",
    "sceptre",
    "spear",
    "flail",
    "bow",
    "staff",
    "twoHandSword",
    "twoHandAxe",
    "twoHandMace",
    "quarterstaff",
    "fishingRod",
    "crossbow",
    "trap",
    "talisman",
  ],
  offhand: ["quiver", "shield", "buckler", "focus"],
  armour: ["gloves", "boots", "bodyArmour", "helmet"],
  jewellery: ["amulet", "ring", "belt"],
};

export const BASE_ITEM_DB: IBaseItemDbType = {
  version: "2026.03.poe2db.snapshot.v1",
    records: [
    {
      baseItemKey: "gloves_001",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/다부진_미트",
    },
    {
      baseItemKey: "gloves_002",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 16,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고정못_미트",
    },
    {
      baseItemKey: "gloves_003",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 22,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/단조한_미트",
    },
    {
      baseItemKey: "gloves_004",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 27,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/발전된_미트",
    },
    {
      baseItemKey: "gloves_005",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 42,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/주조한_미트",
    },
    {
      baseItemKey: "gloves_006",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 56,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정교한_미트",
    },
    {
      baseItemKey: "gloves_007",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 64,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거신_미트",
    },
    {
      baseItemKey: "gloves_008",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 80,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_미트",
    },
    {
      baseItemKey: "gloves_009",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/스웨드_팔보호구",
    },
    {
      baseItemKey: "gloves_010",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 16,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/굳건한_팔보호구",
    },
    {
      baseItemKey: "gloves_011",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 22,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/속박된_팔보호구",
    },
    {
      baseItemKey: "gloves_012",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 36,
      requiredIntelligence: 0,
      levelRequirement: 28,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/절개된_팔보호구",
    },
    {
      baseItemKey: "gloves_013",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 42,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_팔보호구",
    },
    {
      baseItemKey: "gloves_014",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 56,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/섬세한_팔보호구",
    },
    {
      baseItemKey: "gloves_015",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 64,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/굳어진_팔보호구",
    },
    {
      baseItemKey: "gloves_016",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 80,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/아로새긴_팔보호구",
    },
    {
      baseItemKey: "gloves_017",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/찢긴_장갑",
    },
    {
      baseItemKey: "gloves_018",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 17,
      levelRequirement: 12,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/암울한_장갑",
    },
    {
      baseItemKey: "gloves_019",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 22,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/꿰맨_장갑",
    },
    {
      baseItemKey: "gloves_020",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 34,
      levelRequirement: 26,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/보석_박힌_장갑",
    },
    {
      baseItemKey: "gloves_021",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 42,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/복잡한_장갑",
    },
    {
      baseItemKey: "gloves_022",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 56,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/파우아비늘_장갑",
    },
    {
      baseItemKey: "gloves_023",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 64,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/수놓은_장갑",
    },
    {
      baseItemKey: "gloves_024",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 80,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/치장된_장갑",
    },
    {
      baseItemKey: "gloves_025",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 6,
      requiredDexterity: 6,
      requiredIntelligence: 0,
      levelRequirement: 6,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고리_갑옷_건틀릿",
    },
    {
      baseItemKey: "gloves_026",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 13,
      requiredDexterity: 13,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/겹겹의_건틀릿",
    },
    {
      baseItemKey: "gloves_027",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 24,
      requiredDexterity: 24,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/이중_건틀릿",
    },
    {
      baseItemKey: "gloves_028",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_건틀릿",
    },
    {
      baseItemKey: "gloves_029",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 36,
      requiredDexterity: 36,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/윤이_나는_건틀릿",
    },
    {
      baseItemKey: "gloves_030",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 44,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_건틀릿",
    },
    {
      baseItemKey: "gloves_031",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 6,
      requiredDexterity: 0,
      requiredIntelligence: 6,
      levelRequirement: 5,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/밧줄_수갑",
    },
    {
      baseItemKey: "gloves_032",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 13,
      requiredDexterity: 0,
      requiredIntelligence: 13,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/오래된_수갑",
    },
    {
      baseItemKey: "gloves_033",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 24,
      requiredDexterity: 0,
      requiredIntelligence: 24,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/금주물_수갑",
    },
    {
      baseItemKey: "gloves_034",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 0,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/베리시움_수갑",
    },
    {
      baseItemKey: "gloves_035",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 36,
      requiredDexterity: 0,
      requiredIntelligence: 36,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정의로운_수갑",
    },
    {
      baseItemKey: "gloves_036",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 0,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/인장_수갑",
    },
    {
      baseItemKey: "gloves_037",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 6,
      requiredIntelligence: 6,
      levelRequirement: 4,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거즈_싸개",
    },
    {
      baseItemKey: "gloves_038",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 13,
      requiredIntelligence: 13,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/리넨_싸개",
    },
    {
      baseItemKey: "gloves_039",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 24,
      requiredIntelligence: 24,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/나선_싸개",
    },
    {
      baseItemKey: "gloves_040",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/버클_싸개",
    },
    {
      baseItemKey: "gloves_041",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 36,
      requiredIntelligence: 36,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은밀한_싸개",
    },
    {
      baseItemKey: "gloves_042",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 44,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/특수_싸개",
    },
    {
      baseItemKey: "gloves_043",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_소맷부리",
    },
    {
      baseItemKey: "gloves_044",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 56,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_미트",
    },
    {
      baseItemKey: "gloves_045",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 64,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우아한_미트",
    },
    {
      baseItemKey: "gloves_046",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고대_미트",
    },
    {
      baseItemKey: "gloves_047",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 73,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/깃털_미트",
    },
    {
      baseItemKey: "gloves_048",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 56,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사냥_팔보호구",
    },
    {
      baseItemKey: "gloves_049",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 64,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/재빠른_팔보호구",
    },
    {
      baseItemKey: "gloves_050",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/제련된_팔보호구",
    },
    {
      baseItemKey: "gloves_051",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 73,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_팔보호구",
    },
    {
      baseItemKey: "gloves_052",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 56,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/불길한_장갑",
    },
    {
      baseItemKey: "gloves_053",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 64,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/장식된_장갑",
    },
    {
      baseItemKey: "gloves_054",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바로크_장갑",
    },
    {
      baseItemKey: "gloves_055",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 73,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/금_장갑",
    },
    {
      baseItemKey: "gloves_056",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/철사슬_건틀릿",
    },
    {
      baseItemKey: "gloves_057",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 35,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/대장_건틀릿",
    },
    {
      baseItemKey: "gloves_058",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 41,
      requiredDexterity: 41,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/맹신자_건틀릿",
    },
    {
      baseItemKey: "gloves_059",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 0,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/땋은_수갑",
    },
    {
      baseItemKey: "gloves_060",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 0,
      requiredIntelligence: 35,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가보_수갑",
    },
    {
      baseItemKey: "gloves_061",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 41,
      requiredDexterity: 0,
      requiredIntelligence: 41,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_수갑",
    },
    {
      baseItemKey: "gloves_062",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/붕대_싸개",
    },
    {
      baseItemKey: "gloves_063",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 35,
      requiredIntelligence: 35,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/캠브릭_싸개",
    },
    {
      baseItemKey: "gloves_064",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 41,
      requiredIntelligence: 41,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/치장된_싸개",
    },
    {
      baseItemKey: "gloves_065",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 80,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/기사의_미트",
    },
    {
      baseItemKey: "gloves_066",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 87,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_미트",
    },
    {
      baseItemKey: "gloves_067",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 94,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_미트",
    },
    {
      baseItemKey: "gloves_068",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 101,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거대한_미트",
    },
    {
      baseItemKey: "gloves_069",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 80,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/뒤를_쫓는_팔보호구",
    },
    {
      baseItemKey: "gloves_070",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 87,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_팔보호구",
    },
    {
      baseItemKey: "gloves_071",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 94,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_돋친_팔보호구",
    },
    {
      baseItemKey: "gloves_072",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 101,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/광택_나는_팔보호구",
    },
    {
      baseItemKey: "gloves_073",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 80,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/으스스한_장갑",
    },
    {
      baseItemKey: "gloves_074",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 87,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/호화로운_장갑",
    },
    {
      baseItemKey: "gloves_075",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 94,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_장갑",
    },
    {
      baseItemKey: "gloves_076",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 101,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사이렌비늘_장갑",
    },
    {
      baseItemKey: "gloves_077",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 44,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/강철사슬_건틀릿",
    },
    {
      baseItemKey: "gloves_078",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 48,
      requiredDexterity: 48,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/지휘관_건틀릿",
    },
    {
      baseItemKey: "gloves_079",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 52,
      requiredDexterity: 52,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/광신자_건틀릿",
    },
    {
      baseItemKey: "gloves_080",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 55,
      requiredDexterity: 55,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/검은강철_건틀릿",
    },
    {
      baseItemKey: "gloves_081",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 0,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/속박된_수갑",
    },
    {
      baseItemKey: "gloves_082",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 48,
      requiredDexterity: 0,
      requiredIntelligence: 48,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고대의_수갑",
    },
    {
      baseItemKey: "gloves_083",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 52,
      requiredDexterity: 0,
      requiredIntelligence: 52,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/번뜩이는_수갑",
    },
    {
      baseItemKey: "gloves_084",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 55,
      requiredDexterity: 0,
      requiredIntelligence: 55,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/지지자_수갑",
    },
    {
      baseItemKey: "gloves_085",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 44,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/전쟁_싸개",
    },
    {
      baseItemKey: "gloves_086",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 48,
      requiredIntelligence: 48,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우아한_싸개",
    },
    {
      baseItemKey: "gloves_087",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 52,
      requiredIntelligence: 52,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_싸개",
    },
    {
      baseItemKey: "gloves_088",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 55,
      requiredIntelligence: 55,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고정된_싸개",
    },
    // --- body armour ---
    {
      baseItemKey: "body_armour_001",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/녹슨_흉갑",
    },
    {
      baseItemKey: "body_armour_002",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 10,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 4,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/모피_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_003",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 21,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/철_흉갑",
    },
    {
      baseItemKey: "body_armour_004",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 28,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/레이더_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_005",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 34,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 20,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/마라케스_흉갑",
    },
    {
      baseItemKey: "body_armour_006",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 45,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 27,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/강철_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_007",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 54,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/전신_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_008",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 60,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 37,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_흉갑",
    },
    {
      baseItemKey: "body_armour_009",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 72,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거수_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_010",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 80,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 50,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/치프틴_흉갑",
    },
    {
      baseItemKey: "body_armour_011",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 83,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/원형_경기장_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_012",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 92,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 58,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/챔피언_흉갑",
    },
    {
      baseItemKey: "body_armour_013",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/영광의_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_014",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정복자_판금_갑옷",
      implicitMods: ["stun_threshold_inc"],
    },
    {
      baseItemKey: "body_armour_015",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/심연의_흉갑",
      implicitMods: ["life_regen_per_sec"],
    },
    {
      baseItemKey: "body_armour_016",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가죽_조끼",
    },
    {
      baseItemKey: "body_armour_017",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 10,
      requiredIntelligence: 0,
      levelRequirement: 4,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/누비_조끼",
    },
    {
      baseItemKey: "body_armour_018",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 21,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/패스파인더_외투",
    },
    {
      baseItemKey: "body_armour_019",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 28,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/연막의_조끼",
    },
    {
      baseItemKey: "body_armour_020",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 37,
      requiredIntelligence: 0,
      levelRequirement: 22,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/로아가죽_외투",
    },
    {
      baseItemKey: "body_armour_021",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 43,
      requiredIntelligence: 0,
      levelRequirement: 26,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/징_박힌_조끼",
    },
    {
      baseItemKey: "body_armour_022",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 54,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정찰병의_조끼",
    },
    {
      baseItemKey: "body_armour_023",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 59,
      requiredIntelligence: 0,
      levelRequirement: 36,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/뱀_비늘_외투",
    },
    {
      baseItemKey: "body_armour_024",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 72,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/해적_조끼",
    },
    {
      baseItemKey: "body_armour_025",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 82,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/밀수범_외투",
    },
    {
      baseItemKey: "body_armour_026",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 83,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/질주자_조끼",
    },
    {
      baseItemKey: "body_armour_027",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 89,
      requiredIntelligence: 0,
      levelRequirement: 56,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/경화가죽_외투",
    },
    {
      baseItemKey: "body_armour_028",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정교한_조끼",
    },
    {
      baseItemKey: "body_armour_029",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사슬_외투",
      implicitMods: ["debuff_slow_reduced"],
    },
    {
      baseItemKey: "body_armour_030",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/장갑을_두른_조끼",
      implicitMods: ["elemental_ailment_threshold_inc"],
    },
    {
      baseItemKey: "body_armour_031",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/조각난_로브",
    },
    {
      baseItemKey: "body_armour_032",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 11,
      levelRequirement: 5,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/깃털_로브",
    },
    {
      baseItemKey: "body_armour_033",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 21,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사술사의_로브",
    },
    {
      baseItemKey: "body_armour_034",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 28,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/뼈_의복",
    },
    {
      baseItemKey: "body_armour_035",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 37,
      levelRequirement: 22,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/실크_로브",
    },
    {
      baseItemKey: "body_armour_036",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 47,
      levelRequirement: 28,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/케스_의복",
    },
    {
      baseItemKey: "body_armour_037",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 54,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/봉헌된_의복",
    },
    {
      baseItemKey: "body_armour_038",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 65,
      levelRequirement: 40,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/제단_로브",
    },
    {
      baseItemKey: "body_armour_039",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 72,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/엘리멘탈리스트_로브",
    },
    {
      baseItemKey: "body_armour_040",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 78,
      levelRequirement: 49,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/신비한_의복",
    },
    {
      baseItemKey: "body_armour_041",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 83,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/제국_로브",
    },
    {
      baseItemKey: "body_armour_042",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 92,
      levelRequirement: 58,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_의복",
    },
    {
      baseItemKey: "body_armour_043",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/혼란의_의복",
    },
    {
      baseItemKey: "body_armour_044",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/계몽의_로브",
      implicitMods: ["mana_regen_rate_inc"],
    },
    {
      baseItemKey: "body_armour_045",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/비전_의복",
      implicitMods: ["es_recharge_faster"],
    },
    {
      baseItemKey: "body_armour_046",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사슬_갑옷",
    },
    {
      baseItemKey: "body_armour_047",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 13,
      requiredDexterity: 13,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/악한_방어구",
    },
    {
      baseItemKey: "body_armour_048",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 17,
      requiredDexterity: 17,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/방랑자_방어구",
    },
    {
      baseItemKey: "body_armour_049",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 25,
      requiredDexterity: 25,
      requiredIntelligence: 0,
      levelRequirement: 26,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은폐_사슬옷",
    },
    {
      baseItemKey: "body_armour_050",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 31,
      requiredDexterity: 31,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/탐험가_방어구",
    },
    {
      baseItemKey: "body_armour_051",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 34,
      requiredDexterity: 34,
      requiredIntelligence: 0,
      levelRequirement: 37,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/미늘_갑옷",
    },
    {
      baseItemKey: "body_armour_052",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 41,
      requiredDexterity: 41,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/기사_방어구",
    },
    {
      baseItemKey: "body_armour_053",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 44,
      requiredDexterity: 44,
      requiredIntelligence: 0,
      levelRequirement: 50,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/선대의_사슬옷",
    },
    {
      baseItemKey: "body_armour_054",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 46,
      requiredDexterity: 46,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/라멜라_사슬옷",
    },
    {
      baseItemKey: "body_armour_055",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 51,
      requiredDexterity: 51,
      requiredIntelligence: 0,
      levelRequirement: 58,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/검투사_방어구",
    },
    {
      baseItemKey: "body_armour_056",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/영웅의_방어구",
      implicitMods: ["max_life_plus"],
    },
    {
      baseItemKey: "body_armour_057",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/토너먼트_사슬옷",
      implicitMods: ["fire_resist_plus"],
    },
    {
      baseItemKey: "body_armour_058",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/토너먼트_사슬옷",
      implicitMods: ["cold_resist_plus"],
    },
    {
      baseItemKey: "body_armour_059",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/토너먼트_사슬옷",
      implicitMods: ["lightning_resist_plus"],
    },
    {
      baseItemKey: "body_armour_060",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/처형자_방어구",
    },
    {
      baseItemKey: "body_armour_061",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/순례자_법의",
    },
    {
      baseItemKey: "body_armour_062",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 12,
      requiredDexterity: 0,
      requiredIntelligence: 12,
      levelRequirement: 10,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/털가죽_외투",
    },
    {
      baseItemKey: "body_armour_063",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 17,
      requiredDexterity: 0,
      requiredIntelligence: 17,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사슬_법의",
    },
    {
      baseItemKey: "body_armour_064",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 26,
      requiredDexterity: 0,
      requiredIntelligence: 26,
      levelRequirement: 28,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/주술사_외투",
    },
    {
      baseItemKey: "body_armour_065",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 31,
      requiredDexterity: 0,
      requiredIntelligence: 31,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/철갑_법의",
    },
    {
      baseItemKey: "body_armour_066",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 33,
      requiredDexterity: 0,
      requiredIntelligence: 33,
      levelRequirement: 36,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/희생의_외투",
    },
    {
      baseItemKey: "body_armour_067",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 41,
      requiredDexterity: 0,
      requiredIntelligence: 41,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/성직자_법의",
    },
    {
      baseItemKey: "body_armour_068",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 45,
      requiredDexterity: 0,
      requiredIntelligence: 45,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/파도예견자_외투",
    },
    {
      baseItemKey: "body_armour_069",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 46,
      requiredDexterity: 0,
      requiredIntelligence: 46,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/도금된_법의",
    },
    {
      baseItemKey: "body_armour_070",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 48,
      requiredDexterity: 0,
      requiredIntelligence: 48,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/공경받는_외투",
    },
    {
      baseItemKey: "body_armour_071",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/존경받는_법의",
      implicitMods: ["max_elem_resist_plus"],
    },
    {
      baseItemKey: "body_armour_072",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/까마귀_외투",
      implicitMods: ["spirit_plus"],
    },
    {
      baseItemKey: "body_armour_073",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/북극성_법의",
    },
    {
      baseItemKey: "body_armour_074",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은자_의복",
    },
    {
      baseItemKey: "body_armour_075",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 13,
      requiredIntelligence: 13,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/밀랍재질_재킷",
    },
    {
      baseItemKey: "body_armour_076",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 17,
      requiredIntelligence: 17,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/도사_의복",
    },
    {
      baseItemKey: "body_armour_077",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 26,
      requiredIntelligence: 26,
      levelRequirement: 28,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/나그네_재킷",
    },
    {
      baseItemKey: "body_armour_078",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 31,
      requiredIntelligence: 31,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은둔자_의복",
    },
    {
      baseItemKey: "body_armour_079",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 35,
      requiredIntelligence: 35,
      levelRequirement: 39,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/두피수집가의_재킷",
    },
    {
      baseItemKey: "body_armour_080",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 41,
      requiredIntelligence: 41,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/불한당_재킷",
    },
    {
      baseItemKey: "body_armour_081",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 45,
      requiredIntelligence: 45,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고행자_의복",
    },
    {
      baseItemKey: "body_armour_082",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 46,
      requiredIntelligence: 46,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은밀한_재킷",
    },
    {
      baseItemKey: "body_armour_083",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 50,
      requiredIntelligence: 50,
      levelRequirement: 56,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/수도원_의복",
    },
    {
      baseItemKey: "body_armour_084",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고통_재킷",
    },
    {
      baseItemKey: "body_armour_085",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 68,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/헌신자_의복",
      implicitMods: ["chaos_resist_plus"],
    },
    {
      baseItemKey: "body_armour_086",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 73,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/암살자_의복",
      implicitMods: ["move_speed_inc"],
    },
    {
      baseItemKey: "body_armour_087",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 41,
      requiredDexterity: 41,
      requiredIntelligence: 41,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_예복",
    },
    {
      baseItemKey: "body_armour_088",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 72,
      requiredDexterity: 72,
      requiredIntelligence: 72,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/희생의_예복",
      implicitMods: ["corrupted_skill_gem_level"],
    },
    {
      baseItemKey: "body_armour_089",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 72,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/야만인의_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_090",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 77,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/투박한_흉갑",
    },
    {
      baseItemKey: "body_armour_091",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 82,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/모래맹세_흉갑",
    },
    {
      baseItemKey: "body_armour_092",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 86,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우아한_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_093",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 94,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/무거운_판금_갑옷",
    },
    {
      baseItemKey: "body_armour_094",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 98,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/돌_흉갑",
    },
    {
      baseItemKey: "body_armour_095",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 72,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/쪽모이_조끼",
    },
    {
      baseItemKey: "body_armour_096",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 77,
      requiredIntelligence: 0,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사냥_외투",
    },
    {
      baseItemKey: "body_armour_097",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 82,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/승마_외투",
    },
    {
      baseItemKey: "body_armour_098",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 86,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/겹겹의_조끼",
    },
    {
      baseItemKey: "body_armour_099",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 94,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/주자_조끼",
    },
    {
      baseItemKey: "body_armour_100",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 98,
      requiredIntelligence: 0,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/도마뱀비늘_외투",
    },
    {
      baseItemKey: "body_armour_101",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 72,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/새의_로브",
    },
    {
      baseItemKey: "body_armour_102",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 77,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/저주발화자의_로브",
    },
    {
      baseItemKey: "body_armour_103",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 82,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/호화로운_로브",
    },
    {
      baseItemKey: "body_armour_104",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 86,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/강_의복",
    },
    {
      baseItemKey: "body_armour_105",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 94,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/지지자의_의복",
    },
    {
      baseItemKey: "body_armour_106",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 98,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/의식용_로브",
    },
    {
      baseItemKey: "body_armour_107",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 41,
      requiredDexterity: 41,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고리_사슬옷",
    },
    {
      baseItemKey: "body_armour_108",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 43,
      requiredDexterity: 43,
      requiredIntelligence: 0,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/불한당_방어구",
    },
    {
      baseItemKey: "body_armour_109",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 45,
      requiredDexterity: 45,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/방랑자_방어구",
    },
    {
      baseItemKey: "body_armour_110",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 48,
      requiredDexterity: 48,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/덮개_덮은_사슬옷",
    },
    {
      baseItemKey: "body_armour_111",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 52,
      requiredDexterity: 52,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/창시자_방어구",
    },
    {
      baseItemKey: "body_armour_112",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 54,
      requiredDexterity: 54,
      requiredIntelligence: 0,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/황금_사슬옷",
    },
    {
      baseItemKey: "body_armour_113",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 41,
      requiredDexterity: 0,
      requiredIntelligence: 41,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/템플러_법의",
    },
    {
      baseItemKey: "body_armour_114",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 43,
      requiredDexterity: 0,
      requiredIntelligence: 43,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/곰가죽_외투",
    },
    {
      baseItemKey: "body_armour_115",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 45,
      requiredDexterity: 0,
      requiredIntelligence: 45,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/쇠사슬_법의",
    },
    {
      baseItemKey: "body_armour_116",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 48,
      requiredDexterity: 0,
      requiredIntelligence: 48,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/비술사_외투",
    },
    {
      baseItemKey: "body_armour_117",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 52,
      requiredDexterity: 0,
      requiredIntelligence: 52,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_법의",
    },
    {
      baseItemKey: "body_armour_118",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 54,
      requiredDexterity: 0,
      requiredIntelligence: 54,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/심장도륙자_외투",
    },
    {
      baseItemKey: "body_armour_119",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 41,
      requiredIntelligence: 41,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고행자_의복",
    },
    {
      baseItemKey: "body_armour_120",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 43,
      requiredIntelligence: 43,
      levelRequirement: 48,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/기름칠된_재킷",
    },
    {
      baseItemKey: "body_armour_121",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 45,
      requiredIntelligence: 45,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/선교사_의복",
    },
    {
      baseItemKey: "body_armour_122",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 48,
      requiredIntelligence: 48,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/순회자_재킷",
    },
    {
      baseItemKey: "body_armour_123",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 52,
      requiredIntelligence: 52,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/하툰고_의복",
    },
    {
      baseItemKey: "body_armour_124",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 54,
      requiredIntelligence: 54,
      levelRequirement: 62,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/행상_재킷",
    },
    {
      baseItemKey: "body_armour_125",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/병사_흉갑",
    },
    {
      baseItemKey: "body_armour_126",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_판금_갑옷",
      implicitMods: ["life_regen_per_sec"],
    },
    {
      baseItemKey: "body_armour_127",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/웃자알_흉갑",
      implicitMods: ["stun_threshold_inc"],
    },
    {
      baseItemKey: "body_armour_128",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 121,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/전쟁군주_흉갑",
      implicitMods: ["armour_applies_to_elem_damage"],
    },
    {
      baseItemKey: "body_armour_129",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/재빠른_추적자_외투",
      implicitMods: ["debuff_slow_reduced"],
    },
    {
      baseItemKey: "body_armour_130",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/미끄러진_타격_조끼",
    },
    {
      baseItemKey: "body_armour_131",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/아룡_비늘_외투",
      implicitMods: ["elemental_ailment_threshold_inc"],
    },
    {
      baseItemKey: "body_armour_132",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 121,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/해적_외투",
      implicitMods: ["move_speed_inc"],
    },
    {
      baseItemKey: "body_armour_133",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/끔찍한_로브",
    },
    {
      baseItemKey: "body_armour_134",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/흐르는_의복",
      implicitMods: ["mana_regen_rate_inc"],
    },
    {
      baseItemKey: "body_armour_135",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/성찬의_로브",
      implicitMods: ["es_recharge_faster"],
    },
    {
      baseItemKey: "body_armour_136",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 121,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/깃털_의복",
      implicitMods: ["damage_to_mana"],
    },
    {
      baseItemKey: "body_armour_137",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/비겁자_방어구",
      implicitMods: ["max_life_plus"],
    },
    {
      baseItemKey: "body_armour_138",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/연막의_사슬옷",
      implicitMods: ["fire_resist_plus"],
    },
    {
      baseItemKey: "body_armour_139",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/연막의_사슬옷",
      implicitMods: ["cold_resist_plus"],
    },
    {
      baseItemKey: "body_armour_140",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/연막의_사슬옷",
      implicitMods: ["lightning_resist_plus"],
    },
    {
      baseItemKey: "body_armour_141",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/죽음의_사슬옷",
    },
    {
      baseItemKey: "body_armour_142",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/테인_사슬옷",
      implicitMods: ["crit_damage_bonus_reduced"],
    },
    {
      baseItemKey: "body_armour_143",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/늑대가죽_외투",
    },
    {
      baseItemKey: "body_armour_144",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/요술사_외투",
      implicitMods: ["spirit_plus"],
    },
    {
      baseItemKey: "body_armour_145",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/죽음의_외투",
      implicitMods: ["max_elem_resist_plus"],
    },
    {
      baseItemKey: "body_armour_146",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바다폭풍_외투",
      implicitMods: ["damage_to_life_leech"],
    },
    {
      baseItemKey: "body_armour_147",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/매끈한_재킷",
    },
    {
      baseItemKey: "body_armour_148",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/뚜벅이_재킷",
      implicitMods: ["chaos_resist_plus"],
    },
    {
      baseItemKey: "body_armour_149",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/매_조련사의_재킷",
      implicitMods: ["move_speed_inc"],
    },
    {
      baseItemKey: "body_armour_150",
      itemClass: "Body Armour",
      itemClassKey: "bodyArmour",
      equipmentType: "armour",
      subType: "bodyArmour",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 67,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/금욕적인_의복",
      implicitMods: ["elemental_ailment_duration_reduced"],
    },
  ],
};

export const BASE_ITEMS: ReadonlyArray<IBaseItemDefinition> = BASE_ITEM_DB.records.map((record) => {
  return {
    baseItemKey: record.baseItemKey,
    itemClass: record.itemClass,
    itemClassKey: record.itemClassKey,
  };
});

