import type { IBaseItemDefinition } from "./types";

export type IBaseItemEquipmentTypeType = "weapon" | "offhand" | "armour" | "jewellery";
export type IBaseItemSubTypeType =
  | "dagger"
  | "oneHandSword"
  | "oneHandAxe"
  | "oneHandMace"
  | "sceptre"
  | "spear"
  | "flail"
  | "staff"
  | "wand"
  | "bow"
  | "claw"
  | "twoHandSword"
  | "twoHandAxe"
  | "twoHandMace"
  | "quarterstaff"
  | "fishingRod"
  | "crossbow"
  | "trap"
  | "talisman"
  | "quiver"
  | "shield"
  | "buckler"
  | "helmet"
  | "focus"
  | "gloves"
  | "bodyArmour"
  | "boots"
  | "amulet"
  | "ring"
  | "belt";

export interface IBaseItemDbRecordType {
  baseItemKey: string;
  displayName: string;
  itemClass: string;
  itemClassKey: IBaseItemSubTypeType;
  equipmentType: IBaseItemEquipmentTypeType;
  subType: IBaseItemSubTypeType;
  requiredStrength: number;
  requiredDexterity: number;
  requiredIntelligence: number;
  levelRequirement: number;
  source: "poe2db";
  sourceUrl: string;
}

export interface IBaseItemDbType {
  version: string;
  records: ReadonlyArray<IBaseItemDbRecordType>;
}

export const BASE_ITEM_SUB_TYPES_BY_EQUIPMENT: Readonly<
  Record<IBaseItemEquipmentTypeType, ReadonlyArray<IBaseItemSubTypeType>>
> = {
  weapon: [
    "claw",
    "dagger",
    "wand",
    "oneHandSword",
    "oneHandAxe",
    "oneHandMace",
    "sceptre",
    "spear",
    "flail",
    "bow",
    "staff",
    "twoHandSword",
    "twoHandAxe",
    "twoHandMace",
    "quarterstaff",
    "fishingRod",
    "crossbow",
    "trap",
    "talisman",
  ],
  offhand: ["quiver", "shield", "buckler", "focus"],
  armour: ["gloves", "boots", "bodyArmour", "helmet"],
  jewellery: ["amulet", "ring", "belt"],
};

export const BASE_ITEM_DB: IBaseItemDbType = {
  version: "2026.03.poe2db.snapshot.v1",
    records: [
    {
      baseItemKey: "gloves_001",
      displayName: "다부진 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/다부진_미트",
    },
    {
      baseItemKey: "gloves_002",
      displayName: "고정못 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 16,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고정못_미트",
    },
    {
      baseItemKey: "gloves_003",
      displayName: "단조한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 22,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/단조한_미트",
    },
    {
      baseItemKey: "gloves_004",
      displayName: "발전된 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 27,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/발전된_미트",
    },
    {
      baseItemKey: "gloves_005",
      displayName: "주조한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 42,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/주조한_미트",
    },
    {
      baseItemKey: "gloves_006",
      displayName: "정교한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 56,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정교한_미트",
    },
    {
      baseItemKey: "gloves_007",
      displayName: "거신 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 64,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거신_미트",
    },
    {
      baseItemKey: "gloves_008",
      displayName: "우수한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 80,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_미트",
    },
    {
      baseItemKey: "gloves_009",
      displayName: "스웨드 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/스웨드_팔보호구",
    },
    {
      baseItemKey: "gloves_010",
      displayName: "굳건한 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 16,
      requiredIntelligence: 0,
      levelRequirement: 11,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/굳건한_팔보호구",
    },
    {
      baseItemKey: "gloves_011",
      displayName: "속박된 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 22,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/속박된_팔보호구",
    },
    {
      baseItemKey: "gloves_012",
      displayName: "절개된 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 36,
      requiredIntelligence: 0,
      levelRequirement: 28,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/절개된_팔보호구",
    },
    {
      baseItemKey: "gloves_013",
      displayName: "가시 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 42,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_팔보호구",
    },
    {
      baseItemKey: "gloves_014",
      displayName: "섬세한 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 56,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/섬세한_팔보호구",
    },
    {
      baseItemKey: "gloves_015",
      displayName: "굳어진 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 64,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/굳어진_팔보호구",
    },
    {
      baseItemKey: "gloves_016",
      displayName: "아로새긴 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 80,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/아로새긴_팔보호구",
    },
    {
      baseItemKey: "gloves_017",
      displayName: "찢긴 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 1,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/찢긴_장갑",
    },
    {
      baseItemKey: "gloves_018",
      displayName: "암울한 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 17,
      levelRequirement: 12,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/암울한_장갑",
    },
    {
      baseItemKey: "gloves_019",
      displayName: "꿰맨 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 22,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/꿰맨_장갑",
    },
    {
      baseItemKey: "gloves_020",
      displayName: "보석 박힌 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 34,
      levelRequirement: 26,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/보석_박힌_장갑",
    },
    {
      baseItemKey: "gloves_021",
      displayName: "복잡한 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 42,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/복잡한_장갑",
    },
    {
      baseItemKey: "gloves_022",
      displayName: "파우아비늘 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 56,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/파우아비늘_장갑",
    },
    {
      baseItemKey: "gloves_023",
      displayName: "수놓은 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 64,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/수놓은_장갑",
    },
    {
      baseItemKey: "gloves_024",
      displayName: "치장된 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 80,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/치장된_장갑",
    },
    {
      baseItemKey: "gloves_025",
      displayName: "고리 갑옷 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 6,
      requiredDexterity: 6,
      requiredIntelligence: 0,
      levelRequirement: 6,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고리_갑옷_건틀릿",
    },
    {
      baseItemKey: "gloves_026",
      displayName: "겹겹의 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 13,
      requiredDexterity: 13,
      requiredIntelligence: 0,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/겹겹의_건틀릿",
    },
    {
      baseItemKey: "gloves_027",
      displayName: "이중 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 24,
      requiredDexterity: 24,
      requiredIntelligence: 0,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/이중_건틀릿",
    },
    {
      baseItemKey: "gloves_028",
      displayName: "판금 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_건틀릿",
    },
    {
      baseItemKey: "gloves_029",
      displayName: "윤이 나는 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 36,
      requiredDexterity: 36,
      requiredIntelligence: 0,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/윤이_나는_건틀릿",
    },
    {
      baseItemKey: "gloves_030",
      displayName: "화려한 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 44,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_건틀릿",
    },
    {
      baseItemKey: "gloves_031",
      displayName: "밧줄 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 6,
      requiredDexterity: 0,
      requiredIntelligence: 6,
      levelRequirement: 5,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/밧줄_수갑",
    },
    {
      baseItemKey: "gloves_032",
      displayName: "오래된 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 13,
      requiredDexterity: 0,
      requiredIntelligence: 13,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/오래된_수갑",
    },
    {
      baseItemKey: "gloves_033",
      displayName: "금주물 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 24,
      requiredDexterity: 0,
      requiredIntelligence: 24,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/금주물_수갑",
    },
    {
      baseItemKey: "gloves_034",
      displayName: "베리시움 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 0,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/베리시움_수갑",
    },
    {
      baseItemKey: "gloves_035",
      displayName: "정의로운 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 36,
      requiredDexterity: 0,
      requiredIntelligence: 36,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/정의로운_수갑",
    },
    {
      baseItemKey: "gloves_036",
      displayName: "인장 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 0,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/인장_수갑",
    },
    {
      baseItemKey: "gloves_037",
      displayName: "거즈 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 6,
      requiredIntelligence: 6,
      levelRequirement: 4,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거즈_싸개",
    },
    {
      baseItemKey: "gloves_038",
      displayName: "리넨 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 13,
      requiredIntelligence: 13,
      levelRequirement: 16,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/리넨_싸개",
    },
    {
      baseItemKey: "gloves_039",
      displayName: "나선 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 24,
      requiredIntelligence: 24,
      levelRequirement: 33,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/나선_싸개",
    },
    {
      baseItemKey: "gloves_040",
      displayName: "버클 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/버클_싸개",
    },
    {
      baseItemKey: "gloves_041",
      displayName: "은밀한 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 36,
      requiredIntelligence: 36,
      levelRequirement: 52,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/은밀한_싸개",
    },
    {
      baseItemKey: "gloves_042",
      displayName: "특수 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 44,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/특수_싸개",
    },
    {
      baseItemKey: "gloves_043",
      displayName: "우수한 소맷부리",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_소맷부리",
    },
    {
      baseItemKey: "gloves_044",
      displayName: "판금 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 56,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/판금_미트",
    },
    {
      baseItemKey: "gloves_045",
      displayName: "우아한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 64,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우아한_미트",
    },
    {
      baseItemKey: "gloves_046",
      displayName: "고대 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 67,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고대_미트",
    },
    {
      baseItemKey: "gloves_047",
      displayName: "깃털 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 73,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/깃털_미트",
    },
    {
      baseItemKey: "gloves_048",
      displayName: "사냥 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 56,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사냥_팔보호구",
    },
    {
      baseItemKey: "gloves_049",
      displayName: "재빠른 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 64,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/재빠른_팔보호구",
    },
    {
      baseItemKey: "gloves_050",
      displayName: "제련된 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 67,
      requiredIntelligence: 0,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/제련된_팔보호구",
    },
    {
      baseItemKey: "gloves_051",
      displayName: "가시 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 73,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_팔보호구",
    },
    {
      baseItemKey: "gloves_052",
      displayName: "불길한 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 56,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/불길한_장갑",
    },
    {
      baseItemKey: "gloves_053",
      displayName: "장식된 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 64,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/장식된_장갑",
    },
    {
      baseItemKey: "gloves_054",
      displayName: "바로크 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 67,
      levelRequirement: 54,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바로크_장갑",
    },
    {
      baseItemKey: "gloves_055",
      displayName: "금 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 73,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/금_장갑",
    },
    {
      baseItemKey: "gloves_056",
      displayName: "철사슬 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 32,
      requiredIntelligence: 0,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/철사슬_건틀릿",
    },
    {
      baseItemKey: "gloves_057",
      displayName: "대장 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 35,
      requiredIntelligence: 0,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/대장_건틀릿",
    },
    {
      baseItemKey: "gloves_058",
      displayName: "맹신자 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 41,
      requiredDexterity: 41,
      requiredIntelligence: 0,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/맹신자_건틀릿",
    },
    {
      baseItemKey: "gloves_059",
      displayName: "땋은 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 32,
      requiredDexterity: 0,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/땋은_수갑",
    },
    {
      baseItemKey: "gloves_060",
      displayName: "가보 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 35,
      requiredDexterity: 0,
      requiredIntelligence: 35,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가보_수갑",
    },
    {
      baseItemKey: "gloves_061",
      displayName: "화려한 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 41,
      requiredDexterity: 0,
      requiredIntelligence: 41,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_수갑",
    },
    {
      baseItemKey: "gloves_062",
      displayName: "붕대 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 32,
      requiredIntelligence: 32,
      levelRequirement: 45,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/붕대_싸개",
    },
    {
      baseItemKey: "gloves_063",
      displayName: "캠브릭 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 35,
      requiredIntelligence: 35,
      levelRequirement: 51,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/캠브릭_싸개",
    },
    {
      baseItemKey: "gloves_064",
      displayName: "치장된 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 41,
      requiredIntelligence: 41,
      levelRequirement: 59,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/치장된_싸개",
    },
    {
      baseItemKey: "gloves_065",
      displayName: "기사의 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 80,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/기사의_미트",
    },
    {
      baseItemKey: "gloves_066",
      displayName: "화려한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 87,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/화려한_미트",
    },
    {
      baseItemKey: "gloves_067",
      displayName: "바알 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 94,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_미트",
    },
    {
      baseItemKey: "gloves_068",
      displayName: "거대한 미트",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 101,
      requiredDexterity: 0,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/거대한_미트",
    },
    {
      baseItemKey: "gloves_069",
      displayName: "뒤를 쫓는 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 80,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/뒤를_쫓는_팔보호구",
    },
    {
      baseItemKey: "gloves_070",
      displayName: "우수한 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 87,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우수한_팔보호구",
    },
    {
      baseItemKey: "gloves_071",
      displayName: "가시 돋친 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 94,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/가시_돋친_팔보호구",
    },
    {
      baseItemKey: "gloves_072",
      displayName: "광택 나는 팔보호구",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 101,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/광택_나는_팔보호구",
    },
    {
      baseItemKey: "gloves_073",
      displayName: "으스스한 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 80,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/으스스한_장갑",
    },
    {
      baseItemKey: "gloves_074",
      displayName: "호화로운 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 87,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/호화로운_장갑",
    },
    {
      baseItemKey: "gloves_075",
      displayName: "바알 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 94,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_장갑",
    },
    {
      baseItemKey: "gloves_076",
      displayName: "사이렌비늘 장갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 0,
      requiredIntelligence: 101,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/사이렌비늘_장갑",
    },
    {
      baseItemKey: "gloves_077",
      displayName: "강철사슬 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 44,
      requiredIntelligence: 0,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/강철사슬_건틀릿",
    },
    {
      baseItemKey: "gloves_078",
      displayName: "지휘관 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 48,
      requiredDexterity: 48,
      requiredIntelligence: 0,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/지휘관_건틀릿",
    },
    {
      baseItemKey: "gloves_079",
      displayName: "광신자 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 52,
      requiredDexterity: 52,
      requiredIntelligence: 0,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/광신자_건틀릿",
    },
    {
      baseItemKey: "gloves_080",
      displayName: "검은강철 건틀릿",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 55,
      requiredDexterity: 55,
      requiredIntelligence: 0,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/검은강철_건틀릿",
    },
    {
      baseItemKey: "gloves_081",
      displayName: "속박된 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 44,
      requiredDexterity: 0,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/속박된_수갑",
    },
    {
      baseItemKey: "gloves_082",
      displayName: "고대의 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 48,
      requiredDexterity: 0,
      requiredIntelligence: 48,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고대의_수갑",
    },
    {
      baseItemKey: "gloves_083",
      displayName: "번뜩이는 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 52,
      requiredDexterity: 0,
      requiredIntelligence: 52,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/번뜩이는_수갑",
    },
    {
      baseItemKey: "gloves_084",
      displayName: "지지자 수갑",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 55,
      requiredDexterity: 0,
      requiredIntelligence: 55,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/지지자_수갑",
    },
    {
      baseItemKey: "gloves_085",
      displayName: "전쟁 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 44,
      requiredIntelligence: 44,
      levelRequirement: 65,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/전쟁_싸개",
    },
    {
      baseItemKey: "gloves_086",
      displayName: "우아한 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 48,
      requiredIntelligence: 48,
      levelRequirement: 70,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/우아한_싸개",
    },
    {
      baseItemKey: "gloves_087",
      displayName: "바알 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 52,
      requiredIntelligence: 52,
      levelRequirement: 75,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/바알_싸개",
    },
    {
      baseItemKey: "gloves_088",
      displayName: "고정된 싸개",
      itemClass: "Gloves",
      itemClassKey: "gloves",
      equipmentType: "armour",
      subType: "gloves",
      requiredStrength: 0,
      requiredDexterity: 55,
      requiredIntelligence: 55,
      levelRequirement: 80,
      source: "poe2db",
      sourceUrl: "https://poe2db.tw/kr/고정된_싸개",
    },
  ],
};

export const BASE_ITEMS: ReadonlyArray<IBaseItemDefinition> = BASE_ITEM_DB.records.map((record) => {
  return {
    baseItemKey: record.baseItemKey,
    displayName: record.displayName,
    itemClass: record.itemClass,
    itemClassKey: record.itemClassKey,
  };
});

