/**
 * Weapon classes share the simulator's glove-style attack mod pool until per-class mod tables exist.
 */
const WEAPON_SUB_TYPES_FOR_ATTACK_MODS: readonly IBaseItemSubTypeType[] = [
  "claw",
  "dagger",
  "oneHandSword",
  "oneHandAxe",
  "oneHandMace",
  "sceptre",
  "spear",
  "flail",
  "staff",
  "wand",
  "bow",
  "twoHandSword",
  "twoHandAxe",
  "twoHandMace",
  "quarterstaff",
  "fishingRod",
  "crossbow",
  "trap",
  "talisman",
];

const GLOVES_AND_WEAPON_ATTACK_SUB_TYPES: readonly IBaseItemSubTypeType[] = [
  "gloves",
  ...WEAPON_SUB_TYPES_FOR_ATTACK_MODS,
];

/** 스펠 스태프(`staff`)는 위키 `staff` 열 접두(마나·주문·원소 %)만 쓰고, 장갑식 `Added*Damage` 공격 접두 풀에서 제외한다. */
const WEAPON_ATTACK_SUB_TYPES_EXCLUDING_SPELL_STAFF: readonly IBaseItemSubTypeType[] =
  WEAPON_SUB_TYPES_FOR_ATTACK_MODS.filter((subType) => {
    return subType !== "staff";
  });

const GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF: readonly IBaseItemSubTypeType[] = [
  "gloves",
  ...WEAPON_ATTACK_SUB_TYPES_EXCLUDING_SPELL_STAFF,
];

const HELMET_GLOVES_AND_WEAPON_ATTACK_SUB_TYPES: readonly IBaseItemSubTypeType[] = [
  "helmet",
  ...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES,
];

const HELMET_GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF: readonly IBaseItemSubTypeType[] = [
  "helmet",
  ...GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF,
];

/** `ItemFoundRarityIncrease` 접미 — 위키 `mod_spawn_weights` 합집합(ring, amulet, gloves, boots, helmet). 무기 없음. */
const RING_AMULET_BOOTS_HELMET_GLOVES_SUB_TYPES: readonly IBaseItemSubTypeType[] = [
  "ring",
  "amulet",
  "boots",
  "helmet",
  "gloves",
];

/**
 * `ItemFoundRarityIncreasePrefix` 접두 — 반지·목걸이는 전 티어.
 * 투구는 PoE2DB상 최상위 2티어(`Prefix4_`, `Prefix5`)가 `helmet` 스폰 없음 → 추출 시 `applyPoe2dbWikiSpawnPostCorrections`.
 */
const RING_AMULET_HELMET_SUB_TYPES: readonly IBaseItemSubTypeType[] = ["ring", "amulet", "helmet"];

export const MOD_DB: { readonly version: string; readonly records: ReadonlyArray<IModDbRecordType> } = {
  version: "0.1.0",
  records: [

    // =========================================================================
    // Body Armour — Prefixes
    // =========================================================================

    {
      modKey: "prefix_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: [],
      modTags: ["생명력"],
      tierCount: 13,
      maxLevelRequirement: 80,
      totalWeight: 13000,
      nameTemplateKey: "prefix_max_life",
      modFamilyKey: "IncreasedLife",
      modDomain: 1,
    },
    {
      modKey: "prefix_max_es",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "focus"],
      requiredItemTags: ["int"],
      modTags: ["방어막"],
      tierCount: 11,
      maxLevelRequirement: 79,
      totalWeight: 11000,
      nameTemplateKey: "prefix_max_es",
    },
    {
      modKey: "prefix_inc_es",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "focus"],
      requiredItemTags: ["int"],
      modTags: ["방어막"],
      tierCount: 8,
      maxLevelRequirement: 75,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_es",
    },
    {
      modKey: "prefix_inc_es_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["int"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_es_max_life",
    },
    {
      modKey: "prefix_inc_es_max_mana",
      modType: "prefix",
      /** PoE2DB: `BaseLocalDefencesAndMana`는 Helmets·Foci 풀에만 존재(몸통·장갑·장화 없음). */
      applicableSubTypes: ["helmet", "focus"],
      requiredItemTags: ["int"],
      modTags: ["마나", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_es_max_mana",
      modFamilyKey: "BaseLocalDefencesAndMana",
    },
    {
      modKey: "prefix_max_es_inc_es",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "focus"],
      requiredItemTags: ["int"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_max_es_inc_es",
    },
    {
      modKey: "prefix_phys_thorns",
      modType: "prefix",
      /** 위키 Thorns(`AttackerTakesDamage*`): 몸통·방패·허리만 — 장갑·장화·투구 없음. */
      applicableSubTypes: ["bodyArmour", "shield", "buckler", "belt"],
      requiredItemTags: [],
      modTags: ["근접", "물리"],
      tierCount: 7,
      maxLevelRequirement: 74,
      totalWeight: 7000,
      nameTemplateKey: "prefix_phys_thorns",
    },
    {
      modKey: "prefix_spirit",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 8,
      maxLevelRequirement: 78,
      totalWeight: 3000,
      nameTemplateKey: "prefix_spirit",
    },

    // =========================================================================
    // Body Armour — Suffixes
    // =========================================================================

    {
      modKey: "suffix_intelligence",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "focus", "ring", "amulet", "belt"],
      requiredItemTags: ["int"],
      modTags: ["능력치"],
      tierCount: 9,
      maxLevelRequirement: 81,
      totalWeight: 9000,
      nameTemplateKey: "suffix_intelligence",
    },
    {
      modKey: "suffix_fire_res",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: [],
      modTags: ["원소", "화염", "저항"],
      tierCount: 8,
      maxLevelRequirement: 82,
      totalWeight: 8000,
      nameTemplateKey: "suffix_fire_res",
    },
    {
      modKey: "suffix_cold_res",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: [],
      modTags: ["원소", "냉기", "저항"],
      tierCount: 8,
      maxLevelRequirement: 82,
      totalWeight: 8000,
      nameTemplateKey: "suffix_cold_res",
    },
    {
      modKey: "suffix_lightning_res",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: [],
      modTags: ["원소", "번개", "저항"],
      tierCount: 8,
      maxLevelRequirement: 82,
      totalWeight: 8000,
      nameTemplateKey: "suffix_lightning_res",
    },
    {
      modKey: "suffix_chaos_res",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: [],
      modTags: ["카오스", "저항"],
      tierCount: 6,
      maxLevelRequirement: 81,
      totalWeight: 1500,
      nameTemplateKey: "suffix_chaos_res",
    },
    {
      modKey: "suffix_reduced_attr_req",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 5,
      maxLevelRequirement: 60,
      totalWeight: 5000,
      nameTemplateKey: "suffix_reduced_attr_req",
    },
    {
      modKey: "suffix_stun_threshold",
      modType: "suffix",
      /** 위키 `StunThreshold` 스폰: 몸통·장화·허리띠·방패 — 투구·장갑 없음. */
      applicableSubTypes: ["bodyArmour", "boots", "belt", "shield", "buckler"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 11,
      maxLevelRequirement: 72,
      totalWeight: 8800,
      nameTemplateKey: "suffix_stun_threshold",
    },
    {
      modKey: "suffix_crit_chance",
      modType: "suffix",
      /** 위키 `CriticalStrikeChance1–6` — 투구·목걸이 전역 치명타 확률(동일 mod_groups의 무기·궁술·함정 등은 제외). */
      applicableSubTypes: ["helmet", "amulet"],
      requiredItemTags: [],
      modTags: ["치명타"],
      tierCount: 6,
      maxLevelRequirement: 72,
      totalWeight: 3875,
      nameTemplateKey: "suffix_crit_chance",
      modFamilyKey: "CriticalStrikeChanceIncrease",
    },
    {
      modKey: "suffix_life_regen",
      modType: "suffix",
      /** 위키 `LifeRegeneration` 스폰 합집합에서 `gloves` 제외; 투구 슬롯은 시뮬에서 제외. */
      applicableSubTypes: ["bodyArmour", "boots", "belt", "amulet", "ring"],
      requiredItemTags: [],
      modTags: ["생명력"],
      tierCount: 11,
      maxLevelRequirement: 81,
      totalWeight: 11000,
      nameTemplateKey: "suffix_life_regen",
    },
    {
      modKey: "suffix_reduced_bleed_duration",
      modType: "suffix",
      /** 위키 `ReducedBleedDuration*` — `mods.mod_groups` `ReducedAilmentDuration` (PoE2DB는 출혈·중독·점화 3줄 묶음 표기). */
      applicableSubTypes: ["bodyArmour"],
      requiredItemTags: [],
      modTags: ["물리", "상태 이상"],
      modFamilyKey: "ReducedAilmentDuration",
      tierCount: 5,
      maxLevelRequirement: 76,
      totalWeight: 2500,
      nameTemplateKey: "suffix_reduced_bleed_duration",
    },
    {
      modKey: "suffix_reduced_poison_duration",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour"],
      requiredItemTags: [],
      modTags: ["카오스", "상태 이상"],
      modFamilyKey: "ReducedAilmentDuration",
      tierCount: 5,
      maxLevelRequirement: 76,
      totalWeight: 2500,
      nameTemplateKey: "suffix_reduced_poison_duration",
    },
    {
      modKey: "suffix_reduced_ignite_duration",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour"],
      requiredItemTags: [],
      modTags: ["원소", "화염", "상태 이상"],
      modFamilyKey: "ReducedAilmentDuration",
      tierCount: 5,
      maxLevelRequirement: 76,
      totalWeight: 2500,
      nameTemplateKey: "suffix_reduced_ignite_duration",
    },
    {
      modKey: "suffix_es_recharge_rate",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "focus"],
      requiredItemTags: ["int"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 81,
      totalWeight: 6000,
      nameTemplateKey: "suffix_es_recharge_rate",
    },

    // =========================================================================
    // Gloves / helmet / boots — Prefixes: Max Mana (Body Armour는 PoE2DB·위키 풀에 없음)
    // =========================================================================

    {
      modKey: "prefix_max_mana",
      modType: "prefix",
      applicableSubTypes: ["gloves", "boots", "helmet"],
      requiredItemTags: [],
      modTags: ["마나"],
      tierCount: 9,
      maxLevelRequirement: 60,
      totalWeight: 9000,
      nameTemplateKey: "prefix_max_mana",
    },

    // =========================================================================
    // Gloves — Prefixes: Armour (STR only)
    // =========================================================================

    {
      modKey: "prefix_max_armour",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str"],
      modTags: ["방어막"],
      tierCount: 10,
      maxLevelRequirement: 80,
      totalWeight: 10000,
      nameTemplateKey: "prefix_max_armour",
    },
    {
      modKey: "prefix_inc_armour",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour",
    },
    {
      modKey: "prefix_inc_armour_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour_max_life",
    },

    // =========================================================================
    // Gloves — Prefixes: Evasion (DEX only)
    // =========================================================================

    {
      modKey: "prefix_max_evasion",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex"],
      modTags: ["방어막"],
      tierCount: 9,
      maxLevelRequirement: 70,
      totalWeight: 9000,
      nameTemplateKey: "prefix_max_evasion",
    },
    {
      modKey: "prefix_inc_evasion",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_evasion",
    },
    {
      modKey: "prefix_inc_evasion_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_evasion_max_life",
    },

    // =========================================================================
    // Gloves — Prefixes: Armour + Evasion (STR+DEX hybrid)
    // =========================================================================

    {
      modKey: "prefix_armour_evasion_flat",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "dex"],
      modTags: ["방어막"],
      tierCount: 8,
      maxLevelRequirement: 75,
      totalWeight: 8000,
      nameTemplateKey: "prefix_armour_evasion_flat",
    },
    {
      modKey: "prefix_inc_armour_evasion",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "dex"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour_evasion",
    },
    {
      modKey: "prefix_inc_armour_evasion_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "dex"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour_evasion_max_life",
    },

    // =========================================================================
    // Gloves — Prefixes: Armour + Energy Shield (STR+INT hybrid)
    // =========================================================================

    {
      modKey: "prefix_armour_es_flat",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "int"],
      modTags: ["방어막"],
      tierCount: 8,
      maxLevelRequirement: 75,
      totalWeight: 8000,
      nameTemplateKey: "prefix_armour_es_flat",
    },
    {
      modKey: "prefix_inc_armour_es",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "int"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour_es",
    },
    {
      modKey: "prefix_inc_armour_es_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str", "int"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_armour_es_max_life",
    },

    // =========================================================================
    // Gloves — Prefixes: Evasion + Energy Shield (DEX+INT hybrid)
    // =========================================================================

    {
      modKey: "prefix_evasion_es_flat",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex", "int"],
      modTags: ["방어막"],
      tierCount: 8,
      maxLevelRequirement: 75,
      totalWeight: 8000,
      nameTemplateKey: "prefix_evasion_es_flat",
    },
    {
      modKey: "prefix_inc_evasion_es",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex", "int"],
      modTags: ["방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_evasion_es",
    },
    {
      modKey: "prefix_inc_evasion_es_max_life",
      modType: "prefix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex", "int"],
      modTags: ["생명력", "방어막"],
      tierCount: 6,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_evasion_es_max_life",
    },

    // =========================================================================
    // Gloves — Prefixes: Attack Damage (all types)
    // =========================================================================

    {
      modKey: "prefix_added_phys_damage_attack",
      modType: "prefix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF],
      requiredItemTags: [],
      modTags: ["근접", "물리", "공격"],
      tierCount: 9,
      maxLevelRequirement: 75,
      totalWeight: 7500,
      nameTemplateKey: "prefix_added_phys_damage_attack",
    },
    {
      modKey: "prefix_added_fire_damage_attack",
      modType: "prefix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF],
      requiredItemTags: [],
      modTags: ["원소", "화염", "공격"],
      tierCount: 9,
      maxLevelRequirement: 75,
      totalWeight: 3900,
      nameTemplateKey: "prefix_added_fire_damage_attack",
    },
    {
      modKey: "prefix_added_cold_damage_attack",
      modType: "prefix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF],
      requiredItemTags: [],
      modTags: ["원소", "냉기", "공격"],
      tierCount: 9,
      maxLevelRequirement: 75,
      totalWeight: 3900,
      nameTemplateKey: "prefix_added_cold_damage_attack",
    },
    {
      modKey: "prefix_added_lightning_damage_attack",
      modType: "prefix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF],
      requiredItemTags: [],
      modTags: ["원소", "번개", "공격"],
      tierCount: 9,
      maxLevelRequirement: 75,
      totalWeight: 3900,
      nameTemplateKey: "prefix_added_lightning_damage_attack",
    },
    {
      modKey: "prefix_accuracy",
      modType: "prefix",
      applicableSubTypes: [
        ...HELMET_GLOVES_AND_WEAPON_ATTACK_NO_SPELL_STAFF,
        "ring",
        "amulet",
        "quiver",
      ],
      requiredItemTags: [],
      modTags: ["공격"],
      tierCount: 9,
      maxLevelRequirement: 76,
      totalWeight: 6200,
      nameTemplateKey: "prefix_accuracy",
    },
    {
      modKey: "prefix_inc_spell_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["시전"],
      tierCount: 8,
      maxLevelRequirement: 80,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_spell_damage_staff",
      modFamilyKey: "WeaponCasterDamagePrefix",
    },
    {
      modKey: "prefix_inc_spell_damage_wand_focus",
      modType: "prefix",
      applicableSubTypes: ["wand", "focus"],
      requiredItemTags: [],
      modTags: ["시전"],
      tierCount: 8,
      maxLevelRequirement: 80,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_spell_damage_wand_focus",
      modFamilyKey: "WeaponCasterDamagePrefix",
    },
    {
      /** 위키 `IncreasedManaTwoHandWeapon*` 중 Cargo `staff` 스폰 양수인 티 8개(2_/3_/8_/12 등 일부 티는 스태프 열 없음). */
      modKey: "prefix_max_mana_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["마나"],
      tierCount: 8,
      maxLevelRequirement: 70,
      totalWeight: 8000,
      nameTemplateKey: "prefix_max_mana_staff",
      modFamilyKey: "IncreasedMana",
    },
    {
      modKey: "prefix_spell_damage_and_mana_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["시전", "마나"],
      tierCount: 7,
      maxLevelRequirement: 79,
      totalWeight: 7000,
      nameTemplateKey: "prefix_spell_damage_and_mana_staff",
      modFamilyKey: "SpellDamageAndMana",
    },
    {
      modKey: "prefix_spell_damage_and_mana_wand_focus",
      modType: "prefix",
      applicableSubTypes: ["wand", "focus"],
      requiredItemTags: [],
      modTags: ["시전", "마나"],
      tierCount: 7,
      maxLevelRequirement: 79,
      totalWeight: 7000,
      nameTemplateKey: "prefix_spell_damage_and_mana_wand_focus",
      modFamilyKey: "SpellDamageAndMana",
    },
    {
      modKey: "prefix_inc_weapon_fire_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "화염", "시전"],
      tierCount: 6,
      maxLevelRequirement: 70,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_weapon_fire_damage_staff",
      modFamilyKey: "WeaponDamageTypePrefix",
    },
    {
      modKey: "prefix_inc_weapon_cold_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "냉기", "시전"],
      tierCount: 6,
      maxLevelRequirement: 81,
      totalWeight: 6000,
      nameTemplateKey: "prefix_inc_weapon_cold_damage_staff",
      modFamilyKey: "WeaponDamageTypePrefix",
    },
    {
      modKey: "prefix_inc_weapon_lightning_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "번개", "시전"],
      tierCount: 8,
      maxLevelRequirement: 81,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_weapon_lightning_damage_staff",
      modFamilyKey: "WeaponDamageTypePrefix",
    },
    {
      modKey: "prefix_inc_weapon_phys_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["물리", "시전"],
      tierCount: 8,
      maxLevelRequirement: 81,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_weapon_phys_damage_staff",
      modFamilyKey: "WeaponDamageTypePrefix",
    },
    {
      modKey: "prefix_inc_weapon_chaos_damage_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["카오스", "시전"],
      tierCount: 8,
      maxLevelRequirement: 81,
      totalWeight: 8000,
      nameTemplateKey: "prefix_inc_weapon_chaos_damage_staff",
      modFamilyKey: "WeaponDamageTypePrefix",
    },
    {
      modKey: "prefix_gain_as_extra_fire_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "화염", "시전"],
      tierCount: 6,
      maxLevelRequirement: 80,
      totalWeight: 6000,
      nameTemplateKey: "prefix_gain_as_extra_fire_staff",
      modFamilyKey: "FireDamage",
    },
    {
      modKey: "prefix_gain_as_extra_cold_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "냉기", "시전"],
      tierCount: 6,
      maxLevelRequirement: 80,
      totalWeight: 6000,
      nameTemplateKey: "prefix_gain_as_extra_cold_staff",
      modFamilyKey: "ColdDamage",
    },
    {
      modKey: "prefix_gain_as_extra_lightning_staff",
      modType: "prefix",
      applicableSubTypes: ["staff"],
      requiredItemTags: [],
      modTags: ["원소", "번개", "시전"],
      tierCount: 6,
      maxLevelRequirement: 80,
      totalWeight: 6000,
      nameTemplateKey: "prefix_gain_as_extra_lightning_staff",
      modFamilyKey: "LightningDamage",
    },

    // =========================================================================
    // Gloves — Suffixes: Stat Attributes
    // =========================================================================

    {
      modKey: "suffix_strength",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: ["str"],
      modTags: ["능력치"],
      tierCount: 9,
      maxLevelRequirement: 81,
      totalWeight: 9000,
      nameTemplateKey: "suffix_strength",
    },
    {
      modKey: "suffix_dexterity",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet", "ring", "amulet", "belt"],
      requiredItemTags: ["dex"],
      modTags: ["능력치"],
      tierCount: 9,
      maxLevelRequirement: 83,
      totalWeight: 9000,
      nameTemplateKey: "suffix_dexterity",
    },

    // =========================================================================
    // Gloves — Suffixes: Attack & Utility (all types)
    // =========================================================================

    {
      modKey: "suffix_melee_skill_levels",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["공격"],
      tierCount: 2,
      maxLevelRequirement: 41,
      totalWeight: 750,
      nameTemplateKey: "suffix_melee_skill_levels",
    },
    {
      modKey: "suffix_life_leech_from_phys",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["생명력", "물리", "공격"],
      tierCount: 5,
      maxLevelRequirement: 83,
      totalWeight: 5000,
      nameTemplateKey: "suffix_life_leech_from_phys",
    },
    {
      modKey: "suffix_mana_leech_from_phys",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["마나", "물리", "공격"],
      tierCount: 5,
      maxLevelRequirement: 81,
      totalWeight: 5000,
      nameTemplateKey: "suffix_mana_leech_from_phys",
    },
    {
      modKey: "suffix_life_on_kill",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["생명력"],
      tierCount: 8,
      maxLevelRequirement: 77,
      totalWeight: 6000,
      nameTemplateKey: "suffix_life_on_kill",
    },
    {
      modKey: "suffix_mana_on_kill",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["마나"],
      tierCount: 8,
      maxLevelRequirement: 78,
      totalWeight: 6000,
      nameTemplateKey: "suffix_mana_on_kill",
    },
    {
      modKey: "suffix_life_on_hit",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["생명력", "공격"],
      tierCount: 4,
      maxLevelRequirement: 40,
      totalWeight: 4000,
      nameTemplateKey: "suffix_life_on_hit",
    },
    {
      modKey: "suffix_attack_speed",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["공격", "속도"],
      tierCount: 4,
      maxLevelRequirement: 60,
      totalWeight: 2000,
      nameTemplateKey: "suffix_attack_speed",
    },
    {
      modKey: "suffix_crit_damage_bonus",
      modType: "suffix",
      applicableSubTypes: [...GLOVES_AND_WEAPON_ATTACK_SUB_TYPES],
      requiredItemTags: [],
      modTags: ["치명타"],
      tierCount: 5,
      maxLevelRequirement: 59,
      totalWeight: 3750,
      nameTemplateKey: "suffix_crit_damage_bonus",
    },
    {
      modKey: "prefix_item_rarity",
      modType: "prefix",
      applicableSubTypes: [...RING_AMULET_HELMET_SUB_TYPES],
      requiredItemTags: [],
      modTags: [],
      tierCount: 5,
      maxLevelRequirement: 81,
      totalWeight: 5000,
      nameTemplateKey: "prefix_item_rarity",
    },
    {
      modKey: "suffix_item_rarity",
      modType: "suffix",
      applicableSubTypes: [...RING_AMULET_BOOTS_HELMET_GLOVES_SUB_TYPES],
      requiredItemTags: [],
      modTags: [],
      tierCount: 5,
      maxLevelRequirement: 75,
      totalWeight: 5000,
      nameTemplateKey: "suffix_item_rarity",
    },
    {
      modKey: "suffix_minion_spell_gem_level",
      modType: "suffix",
      /** 위키 `GlobalMinionSpellSkillGemLevel*`(비무기): 투구·목걸이 — 상위 티는 목걸이 전용. 스폰 가중치 숫자는 `wikiModTierMerge`+Cargo(플래그형 value)로 합성. */
      applicableSubTypes: ["helmet", "amulet"],
      requiredItemTags: [],
      modTags: ["소환수", "시전"],
      craftTags: ["minion", "spell"],
      tierCount: 3,
      maxLevelRequirement: 75,
      totalWeight: 850,
      nameTemplateKey: "suffix_minion_spell_gem_level",
      modFamilyKey: "IncreaseSocketedGemLevel",
    },

    // =========================================================================
    // Gloves — Suffixes: Defence-stat Specific
    // =========================================================================

    {
      modKey: "suffix_armour_to_elemental",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["str"],
      modTags: ["방어막", "원소"],
      tierCount: 6,
      maxLevelRequirement: 81,
      totalWeight: 6000,
      nameTemplateKey: "suffix_armour_to_elemental",
    },
    {
      modKey: "suffix_fortify_from_evasion",
      modType: "suffix",
      applicableSubTypes: ["bodyArmour", "gloves", "boots", "helmet"],
      requiredItemTags: ["dex"],
      modTags: ["방어막"],
      tierCount: 5,
      maxLevelRequirement: 66,
      totalWeight: 5000,
      nameTemplateKey: "suffix_fortify_from_evasion",
    },

    // =========================================================================
    // Body Armour — Corrupted Implicit Suffixes (훼손된 속성 접미어)
    // Source: AMANAMU / KURGAL / ULAMAN vaal gods
    // weight 0 — only obtainable via corruption, not regular crafting
    // =========================================================================

    {
      modKey: "corrupted_fire_chaos_res",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["원소", "화염", "카오스", "저항"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_fire_chaos_res",
    },
    {
      modKey: "corrupted_str_int",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["능력치"],
      tierCount: 2,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_str_int",
    },
    {
      modKey: "corrupted_str_dex",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["능력치"],
      tierCount: 2,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_str_dex",
    },
    {
      modKey: "corrupted_spirit_retention",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_spirit_retention",
    },
    {
      modKey: "corrupted_reduced_curse_effect",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["시전", "저주"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_reduced_curse_effect",
    },
    {
      modKey: "corrupted_cold_chaos_res",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["원소", "냉기", "카오스", "저항"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_cold_chaos_res",
    },
    {
      modKey: "corrupted_dex_int",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["능력치"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_dex_int",
    },
    {
      modKey: "corrupted_damage_as_mana_cost",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["생명력", "마나"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_damage_as_mana_cost",
    },
    {
      modKey: "corrupted_damage_to_mana_recoup",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["생명력", "마나"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_damage_to_mana_recoup",
    },
    {
      modKey: "corrupted_lightning_chaos_res",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["원소", "번개", "카오스", "저항"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_lightning_chaos_res",
    },
    {
      modKey: "corrupted_reduced_crit_chance_vs_player",
      modType: "corruptedSuffix",
      applicableSubTypes: ["bodyArmour", "gloves"],
      requiredItemTags: [],
      modTags: ["치명타"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_reduced_crit_chance_vs_player",
    },

    // =========================================================================
    // Gloves — Corrupted Implicit Suffixes (장갑 전용)
    // =========================================================================

    {
      modKey: "corrupted_stun_on_hit",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_stun_on_hit",
    },
    {
      modKey: "corrupted_instant_leech",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_instant_leech",
    },
    {
      modKey: "corrupted_mana_cost_efficiency",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["마나"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_mana_cost_efficiency",
    },
    {
      modKey: "corrupted_ailment_intensity",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["상태 이상"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_ailment_intensity",
    },
    {
      modKey: "corrupted_bleed_chance",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_bleed_chance",
    },
    {
      modKey: "corrupted_poison_chance",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_poison_chance",
    },
    {
      modKey: "corrupted_curse_effect_area",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["시전", "저주"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_curse_effect_area",
    },
    {
      modKey: "corrupted_immobilize_buildup",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: [],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_immobilize_buildup",
    },
    {
      modKey: "corrupted_arcane_shadow_on_crit",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["치명타"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_arcane_shadow_on_crit",
    },
    {
      modKey: "corrupted_cast_speed_at_full_life",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["시전", "속도"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_cast_speed_at_full_life",
    },
    {
      modKey: "corrupted_skill_speed_consume_frenzy",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["속도"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_skill_speed_consume_frenzy",
    },
    {
      modKey: "corrupted_lacerate_on_hit",
      modType: "corruptedSuffix",
      applicableSubTypes: ["gloves"],
      requiredItemTags: [],
      modTags: ["물리", "상태 이상"],
      tierCount: 1,
      maxLevelRequirement: 65,
      totalWeight: 0,
      nameTemplateKey: "corrupted_lacerate_on_hit",
    },

  ],
};
